"""Initial migration

Revision ID: a9e4f81425a3
Revises: 
Create Date: 2021-06-03 03:10:02.778086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9e4f81425a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('course', sa.String(length=20), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_level', sa.Integer(), nullable=False),
    sa.Column('user_points', sa.Integer(), nullable=False),
    sa.Column('english_points', sa.Integer(), nullable=False),
    sa.Column('inter_points', sa.Integer(), nullable=False),
    sa.Column('social_points', sa.Integer(), nullable=False),
    sa.Column('math_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('subject_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('math_level', sa.Integer(), nullable=True),
    sa.Column('english_level', sa.Integer(), nullable=True),
    sa.Column('social_level', sa.Integer(), nullable=True),
    sa.Column('inter_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('crowns', sa.Integer(), nullable=True),
    sa.Column('trophies', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('last_subject', sa.String(length=100), nullable=True),
    sa.Column('last_score', sa.Integer(), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=False),
    sa.Column('last_recommendation', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_streak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('streak_points', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_streak')
    op.drop_table('user_progress')
    op.drop_table('user_achievement')
    op.drop_table('subject_level')
    op.drop_table('user')
    # ### end Alembic commands ###
